### ISSUE TITLE
Remake sections of the actual template:

### ISSUE THREAD

**Issue by rivasvict** [rivasvict/wedding-app#16]
- About = Sobre nosotros
- Services = Informacion  y pin de mapa
- Portfolio = Fotos
- Contact = comentario y boton de regalo

@cape3120 Please define the text content here

**Comment by cape3120** [comment]
this paper have the remake section ready 

https://docs.google.com/document/d/1oclrAR25oNrAI3NYHsTrtNTYa_z6BNpeLgTovPMsEBk/edit?usp=sharing

**Comment by cape3120** [comment]
@jobliz this is for you
