### ISSUE TITLE
Add paralax

### ISSUE THREAD

**Issue by rivasvict** [rivasvict/wedding-app#17]
@cape3120 Please define an image of the paralax.

**Comment by cape3120** [comment]
![img_20160806_110336](https://user-images.githubusercontent.com/20747459/28249956-7b649ee2-6a2d-11e7-9023-bcb9b590ee6b.jpg)

![img_20170315_141407](https://user-images.githubusercontent.com/20747459/28249959-81c42276-6a2d-11e7-8e7c-132dc36abc0d.jpg)

![img_20170314_181141](https://user-images.githubusercontent.com/20747459/28249962-8d72bbc8-6a2d-11e7-8dbc-125f732c4aaf.jpg)

![img_20170314_181158](https://user-images.githubusercontent.com/20747459/28249965-94c7db74-6a2d-11e7-90a5-32cd2564a299.jpg)

![2013-03-22 17 58 24](https://user-images.githubusercontent.com/20747459/28249977-b6ad4242-6a2d-11e7-8c08-a0373472660e.jpg)

@vctr90 one of this should work

**Comment by cape3120** [comment]
@vctr90 i like all this pics, the only that i don't love completely is the second one that i like it but don't love it

the other 4 i love its

**Comment by rivasvict** [comment]
Please take a look at this:
https://www.npmjs.com/package/parallax-js
and
http://pixelcog.github.io/parallax.js/
